apiVersion: v1
kind: ConfigMap
metadata:
  name: teste_comunicain-api
data:
  ENVIRONMENT: staging
  NODE_ENV: production
  PORT: '3001'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste_comunicain-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: teste_comunicain-api
  template:
    spec:
      containers:
        - name: teste_comunicain-api
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: teste_comunicain-api-svc
spec:
  selector:
    app: teste_comunicain-api
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teste_comunicain-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teste_comunicain-api
  minReplicas: 1
  maxReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-teste_comunicain
  labels:
    app: redis-teste_comunicain
spec:
  selector:
    matchLabels:
      app: redis-teste_comunicain
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-teste_comunicain
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: redis
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-teste_comunicain-svc
  labels:
    app: redis-teste_comunicain
spec:
  selector:
    app: redis-teste_comunicain
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP
