apiVersion: v1
kind: ConfigMap
metadata:
  name: teste_comunicain-api
data:
  ENVIRONMENT: prod
  NODE_ENV: production
  PORT: '3001'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste_comunicain-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  replicas: 3
  selector:
    matchLabels:
      app: teste_comunicain-api
  template:
    spec:
      containers:
        - name: teste_comunicain-api
          resources:
            requests:
              memory: 350Mi
            limits:
              memory: 650Mi

---
apiVersion: v1
kind: Service
metadata:
  name: teste_comunicain-api-svc
spec:
  selector:
    app: teste_comunicain-api
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: teste_comunicain-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teste_comunicain-api
  minReplicas: 3
  maxReplicas: 5
